export const apiRoutes = {
  GET_ALL_DATA: "/album/get-all-album",
  GET_ALL_ARTIST: "/artist/get-all-artist",
  GET_ALL_SONG: "/song/new-released-song",
  GET_SIGNUP: "/users/signup",
  GET_LOGIN: "/users/login",
  GET_VERIFYTOKEN: "/verify-token",
  FORGOT_PASSWORD: "/admins/forgot-password",
  RESET_PASSWORD: "/admins/reset-password",
  // CHANGE_PASSWORD: "/users/update-user",
  CHANGE_PASSWORD: (userId) => `/users/update-user/${userId}`,
  ADD_FAVOURITES: "/favourite/add-to-favourite",
  GET_ALLFAVORITES: "/favourite/get-all-favourite-current-user",
  GET_SPECIFICFAV: "/favourite/get-favourite-specific-song",
  REMOVE_FAV: "/favourite/remove-favourite",
  GET_GENRE: "/genre/get-all-genre",
  GET_ALLPLAYLIST: "/playlist/get-all-playlist",
  GET_ALL_FAQ: "/faq/get-all-faq",
  CREATE_FAQ: "faq/create-faq",
  REMOVE_FAQ: "/faq/delete-faq",
  GET_PRIVACY: "/editor/get-all-content",
  GET_AUDIO: "/song/audio-song",
  GET_VIDEO: "/song/video-song",
  GLOBAL_SEARCH: "/auth/global-search?query=Adele&page=1&limit=5",
};
